#!/usr/bin/env python3
"""Generate docs/cli/reference.md from the CLI's --help output.

This script shells out to the compiled minifyjs binary, captures
`--help`, and wraps it in a markdown document. It is the only way to
guarantee that the docs and the CLI cannot drift apart.

Usage:

    python tools/docs/generate_cli_reference.py --output docs/cli/reference.md
    python tools/docs/generate_cli_reference.py            # prints to stdout
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def find_binary() -> str:
    """Locate the minifyjs binary to run."""
    candidates = [
        shutil.which("minifyjs"),
        Path(__file__).resolve().parents[2] / "core" / "bin" / "minifyjs",
        Path(__file__).resolve().parents[2] / "core" / "bin" / "minifyjs.exe",
    ]
    for c in candidates:
        if c is None:
            continue
        p = Path(c)
        if p.is_file():
            return str(p)
    print(
        "error: could not find minifyjs binary.\n"
        "Build it first: cd core && go build -o bin/minifyjs ./cmd/minifyjs",
        file=sys.stderr,
    )
    sys.exit(1)


def generate(binary: str) -> str:
    proc = subprocess.run(
        [binary, "--help"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        print(f"error: {binary} --help exited {proc.returncode}",
              file=sys.stderr)
        sys.exit(1)
    help_text = proc.stdout.decode("utf-8")

    version_proc = subprocess.run(
        [binary, "--version"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    version = version_proc.stdout.decode("utf-8").strip()

    return render(help_text, version)


def render(help_text: str, version: str) -> str:
    return (
        "# CLI reference\n\n"
        "This file is generated by `tools/docs/generate_cli_reference.py`.\n"
        "Do not edit it by hand. Regenerate with:\n\n"
        "```console\n"
        "python tools/docs/generate_cli_reference.py --output docs/cli/reference.md\n"
        "```\n\n"
        f"## Version\n\n"
        f"```\n{version}\n```\n\n"
        "## Help output\n\n"
        "```\n"
        f"{help_text.rstrip()}\n"
        "```\n\n"
        "## See also\n\n"
        "- [CLI overview](overview.md)\n"
        "- [Configuration reference](../reference/configuration.md)\n"
        "- [Exit codes](../reference/exit-codes.md)\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate CLI reference")
    parser.add_argument("--output", default=None, help="output file (default: stdout)")
    parser.add_argument("--binary", default=None, help="path to minifyjs binary")
    args = parser.parse_args()

    binary = args.binary or find_binary()
    content = generate(binary)

    if args.output is None:
        sys.stdout.write(content)
        return 0

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())