// Command syntax_matrix walks core/testdata/fixtures/ and produces a
// markdown table showing which ECMAScript version introduced each
// fixture's language feature.
//
// The version metadata is read from a small sidecar file in each
// fixture directory:
//
//	<fixture>/matrix.json  { "es_version": "es2015", "feature": "arrow functions", "notes": "" }
//
// Fixtures without a matrix.json are reported as "unknown" and left
// out of the table.
//
// Usage:
//
//	go run ./tools/syntax_matrix
//	go run ./tools/syntax_matrix --output docs/supported-syntax.md
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type matrixEntry struct {
	ESVersion string `json:"es_version"`
	Feature   string `json:"feature"`
	Notes     string `json:"notes,omitempty"`
}

type row struct {
	Fixture   string
	ESVersion string
	Feature   string
	Notes     string
}

func main() {
	var (
		dir    = flag.String("dir", "", "fixtures directory (default: auto-detect)")
		output = flag.String("output", "", "output markdown file (default: stdout)")
	)
	flag.Parse()

	fixturesDir, err := findFixturesDir(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "syntax_matrix: %v\n", err)
		os.Exit(1)
	}

	rows, err := collect(fixturesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "syntax_matrix: %v\n", err)
		os.Exit(1)
	}

	table := render(rows)

	if *output == "" {
		fmt.Print(table)
		return
	}
	if err := os.WriteFile(*output, []byte(table), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "syntax_matrix: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *output)
}

func findFixturesDir(explicit string) (string, error) {
	if explicit != "" {
		return explicit, nil
	}
	candidates := []string{
		filepath.Join("core", "testdata", "fixtures"),
		filepath.Join("..", "core", "testdata", "fixtures"),
		filepath.Join("..", "..", "core", "testdata", "fixtures"),
	}
	for _, c := range candidates {
		if info, err := os.Stat(c); err == nil && info.IsDir() {
			return c, nil
		}
	}
	return "", fmt.Errorf("could not find fixtures directory; pass --dir")
}

func collect(dir string) ([]row, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var rows []row
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		metaPath := filepath.Join(dir, e.Name(), "matrix.json")
		data, err := os.ReadFile(metaPath)
		if err != nil {
			continue // no metadata, skip
		}
		var m matrixEntry
		if err := json.Unmarshal(data, &m); err != nil {
			fmt.Fprintf(os.Stderr, "syntax_matrix: %s: %v\n", metaPath, err)
			continue
		}
		rows = append(rows, row{
			Fixture:   e.Name(),
			ESVersion: m.ESVersion,
			Feature:   m.Feature,
			Notes:     m.Notes,
		})
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].ESVersion != rows[j].ESVersion {
			return esOrder(rows[i].ESVersion) < esOrder(rows[j].ESVersion)
		}
		return rows[i].Fixture < rows[j].Fixture
	})

	return rows, nil
}

// esOrder returns a numeric sort key for an ES version string.
func esOrder(v string) int {
	v = strings.ToLower(v)
	if !strings.HasPrefix(v, "es") {
		return 9999
	}
	var year int
	if _, err := fmt.Sscanf(v[2:], "%d", &year); err != nil {
		return 9999
	}
	return year
}

func render(rows []row) string {
	var b strings.Builder
	b.WriteString("# Supported syntax\n\n")
	b.WriteString("This file is generated by `tools/syntax_matrix`. Do not edit by hand.\n\n")
	b.WriteString("| ES version | Feature | Fixture | Notes |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, r := range rows {
		b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s |\n",
			r.ESVersion, r.Feature, r.Fixture, r.Notes))
	}
	return b.String()
}